export default {
  standings: [
    {
      stage: "REGULAR_SEASON",
      type: "TOTAL",
      group: null,
      table: [
        {
          position: 1,
          team: {
            id: 78,
            name: "Club Atlético de Madrid",
            crestUrl: "https://crests.football-data.org/78.svg",
          },
          playedGames: 34,
          form: "W,L,W,W,D",
          won: 23,
          draw: 7,
          lost: 4,
          points: 76,
          goalsFor: 61,
          goalsAgainst: 22,
          goalDifference: 39,
        },
        {
          position: 2,
          team: {
            id: 81,
            name: "FC Barcelona",
            crestUrl: "https://crests.football-data.org/81.svg",
          },
          playedGames: 34,
          form: "W,L,W,W,L",
          won: 23,
          draw: 5,
          lost: 6,
          points: 74,
          goalsFor: 80,
          goalsAgainst: 33,
          goalDifference: 47,
        },
        {
          position: 3,
          team: {
            id: 86,
            name: "Real Madrid CF",
            crestUrl: "https://crests.football-data.org/86.svg",
          },
          playedGames: 34,
          form: "W,D,W,D,W",
          won: 22,
          draw: 8,
          lost: 4,
          points: 74,
          goalsFor: 58,
          goalsAgainst: 24,
          goalDifference: 34,
        },
        {
          position: 4,
          team: {
            id: 559,
            name: "Sevilla FC",
            crestUrl: "https://crests.football-data.org/559.svg",
          },
          playedGames: 33,
          form: "W,W,W,W,W",
          won: 22,
          draw: 4,
          lost: 7,
          points: 70,
          goalsFor: 49,
          goalsAgainst: 26,
          goalDifference: 23,
        },
        {
          position: 5,
          team: {
            id: 92,
            name: "Real Sociedad de Fútbol",
            crestUrl: "https://crests.football-data.org/92.svg",
          },
          playedGames: 34,
          form: "L,W,W,L,D",
          won: 14,
          draw: 11,
          lost: 9,
          points: 53,
          goalsFor: 51,
          goalsAgainst: 35,
          goalDifference: 16,
        },
        {
          position: 6,
          team: {
            id: 94,
            name: "Villarreal CF",
            crestUrl: "https://crests.football-data.org/94.svg",
          },
          playedGames: 34,
          form: "W,L,L,W,L",
          won: 13,
          draw: 13,
          lost: 8,
          points: 52,
          goalsFor: 51,
          goalsAgainst: 38,
          goalDifference: 13,
        },
        {
          position: 7,
          team: {
            id: 90,
            name: "Real Betis Balompié",
            crestUrl: "https://crests.football-data.org/90.svg",
          },
          playedGames: 34,
          form: "D,D,D,D,D",
          won: 14,
          draw: 9,
          lost: 11,
          points: 51,
          goalsFor: 43,
          goalsAgainst: 46,
          goalDifference: -3,
        },
        {
          position: 8,
          team: {
            id: 83,
            name: "Granada CF",
            crestUrl: "https://crests.football-data.org/83.svg",
          },
          playedGames: 34,
          form: "L,W,L,W,W",
          won: 13,
          draw: 6,
          lost: 15,
          points: 45,
          goalsFor: 43,
          goalsAgainst: 55,
          goalDifference: -12,
        },
        {
          position: 9,
          team: {
            id: 558,
            name: "RC Celta de Vigo",
            crestUrl: "https://crests.football-data.org/558.svg",
          },
          playedGames: 34,
          form: "W,W,L,D,L",
          won: 11,
          draw: 11,
          lost: 12,
          points: 44,
          goalsFor: 46,
          goalsAgainst: 51,
          goalDifference: -5,
        },
        {
          position: 10,
          team: {
            id: 77,
            name: "Athletic Club",
            crestUrl: "https://crests.football-data.org/77.svg",
          },
          playedGames: 33,
          form: "D,W,D,D,D",
          won: 10,
          draw: 12,
          lost: 11,
          points: 42,
          goalsFor: 43,
          goalsAgainst: 36,
          goalDifference: 7,
        },
        {
          position: 11,
          team: {
            id: 79,
            name: "CA Osasuna",
            crestUrl: "https://crests.football-data.org/79.svg",
          },
          playedGames: 34,
          form: "L,L,W,W,W",
          won: 10,
          draw: 10,
          lost: 14,
          points: 40,
          goalsFor: 31,
          goalsAgainst: 41,
          goalDifference: -10,
        },
        {
          position: 12,
          team: {
            id: 264,
            name: "Cádiz CF",
            crestUrl: "https://crests.football-data.org/264.svg",
          },
          playedGames: 34,
          form: "W,D,L,D,W",
          won: 10,
          draw: 10,
          lost: 14,
          points: 40,
          goalsFor: 29,
          goalsAgainst: 49,
          goalDifference: -20,
        },
        {
          position: 13,
          team: {
            id: 88,
            name: "Levante UD",
            crestUrl: "https://crests.football-data.org/88.svg",
          },
          playedGames: 34,
          form: "L,L,L,L,W",
          won: 9,
          draw: 11,
          lost: 14,
          points: 38,
          goalsFor: 38,
          goalsAgainst: 48,
          goalDifference: -10,
        },
        {
          position: 14,
          team: {
            id: 95,
            name: "Valencia CF",
            crestUrl: "https://crests.football-data.org/95.svg",
          },
          playedGames: 34,
          form: "L,D,L,D,D",
          won: 8,
          draw: 12,
          lost: 14,
          points: 36,
          goalsFor: 43,
          goalsAgainst: 51,
          goalDifference: -8,
        },
        {
          position: 15,
          team: {
            id: 82,
            name: "Getafe CF",
            crestUrl: "https://crests.football-data.org/82.svg",
          },
          playedGames: 34,
          form: "L,W,L,D,L",
          won: 8,
          draw: 10,
          lost: 16,
          points: 34,
          goalsFor: 26,
          goalsAgainst: 40,
          goalDifference: -14,
        },
        {
          position: 16,
          team: {
            id: 250,
            name: "Real Valladolid CF",
            crestUrl: "https://crests.football-data.org/250.svg",
          },
          playedGames: 34,
          form: "D,D,D,D,L",
          won: 5,
          draw: 16,
          lost: 13,
          points: 31,
          goalsFor: 32,
          goalsAgainst: 46,
          goalDifference: -14,
        },
        {
          position: 17,
          team: {
            id: 263,
            name: "Deportivo Alavés",
            crestUrl: "https://crests.football-data.org/263.svg",
          },
          playedGames: 34,
          form: "L,D,W,W,D",
          won: 7,
          draw: 10,
          lost: 17,
          points: 31,
          goalsFor: 28,
          goalsAgainst: 52,
          goalDifference: -24,
        },
        {
          position: 18,
          team: {
            id: 299,
            name: "SD Huesca",
            crestUrl: "https://crests.football-data.org/299.svg",
          },
          playedGames: 34,
          form: "W,L,L,L,W",
          won: 6,
          draw: 12,
          lost: 16,
          points: 30,
          goalsFor: 32,
          goalsAgainst: 50,
          goalDifference: -18,
        },
        {
          position: 19,
          team: {
            id: 285,
            name: "Elche CF",
            crestUrl: "https://crests.football-data.org/285.svg",
          },
          playedGames: 34,
          form: "L,W,D,L,L",
          won: 6,
          draw: 12,
          lost: 16,
          points: 30,
          goalsFor: 29,
          goalsAgainst: 50,
          goalDifference: -21,
        },
        {
          position: 20,
          team: {
            id: 278,
            name: "SD Eibar",
            crestUrl: "https://crests.football-data.org/278.svg",
          },
          playedGames: 34,
          form: "W,L,L,L,L",
          won: 5,
          draw: 11,
          lost: 18,
          points: 26,
          goalsFor: 26,
          goalsAgainst: 46,
          goalDifference: -20,
        },
      ],
    },
    {
      stage: "REGULAR_SEASON",
      type: "HOME",
      group: null,
      table: [
        {
          position: 1,
          team: {
            id: 78,
            name: "Club Atlético de Madrid",
            crestUrl: "https://crests.football-data.org/78.svg",
          },
          playedGames: 17,
          form: "",
          won: 13,
          draw: 3,
          lost: 1,
          points: 42,
          goalsFor: 37,
          goalsAgainst: 9,
          goalDifference: 28,
        },
        {
          position: 2,
          team: {
            id: 86,
            name: "Real Madrid CF",
            crestUrl: "https://crests.football-data.org/86.svg",
          },
          playedGames: 17,
          form: "",
          won: 12,
          draw: 2,
          lost: 3,
          points: 38,
          goalsFor: 29,
          goalsAgainst: 10,
          goalDifference: 19,
        },
        {
          position: 3,
          team: {
            id: 81,
            name: "FC Barcelona",
            crestUrl: "https://crests.football-data.org/81.svg",
          },
          playedGames: 17,
          form: "",
          won: 11,
          draw: 4,
          lost: 2,
          points: 37,
          goalsFor: 43,
          goalsAgainst: 18,
          goalDifference: 25,
        },
        {
          position: 4,
          team: {
            id: 559,
            name: "Sevilla FC",
            crestUrl: "https://crests.football-data.org/559.svg",
          },
          playedGames: 16,
          form: "",
          won: 12,
          draw: 1,
          lost: 3,
          points: 37,
          goalsFor: 25,
          goalsAgainst: 10,
          goalDifference: 15,
        },
        {
          position: 5,
          team: {
            id: 83,
            name: "Granada CF",
            crestUrl: "https://crests.football-data.org/83.svg",
          },
          playedGames: 17,
          form: "",
          won: 9,
          draw: 3,
          lost: 5,
          points: 30,
          goalsFor: 24,
          goalsAgainst: 21,
          goalDifference: 3,
        },
        {
          position: 6,
          team: {
            id: 77,
            name: "Athletic Club",
            crestUrl: "https://crests.football-data.org/77.svg",
          },
          playedGames: 17,
          form: "",
          won: 8,
          draw: 5,
          lost: 4,
          points: 29,
          goalsFor: 27,
          goalsAgainst: 16,
          goalDifference: 11,
        },
        {
          position: 7,
          team: {
            id: 90,
            name: "Real Betis Balompié",
            crestUrl: "https://crests.football-data.org/90.svg",
          },
          playedGames: 17,
          form: "",
          won: 8,
          draw: 5,
          lost: 4,
          points: 29,
          goalsFor: 24,
          goalsAgainst: 20,
          goalDifference: 4,
        },
        {
          position: 8,
          team: {
            id: 92,
            name: "Real Sociedad de Fútbol",
            crestUrl: "https://crests.football-data.org/92.svg",
          },
          playedGames: 17,
          form: "",
          won: 7,
          draw: 6,
          lost: 4,
          points: 27,
          goalsFor: 28,
          goalsAgainst: 20,
          goalDifference: 8,
        },
        {
          position: 9,
          team: {
            id: 94,
            name: "Villarreal CF",
            crestUrl: "https://crests.football-data.org/94.svg",
          },
          playedGames: 17,
          form: "",
          won: 7,
          draw: 6,
          lost: 4,
          points: 27,
          goalsFor: 23,
          goalsAgainst: 19,
          goalDifference: 4,
        },
        {
          position: 10,
          team: {
            id: 558,
            name: "RC Celta de Vigo",
            crestUrl: "https://crests.football-data.org/558.svg",
          },
          playedGames: 17,
          form: "",
          won: 8,
          draw: 3,
          lost: 6,
          points: 27,
          goalsFor: 27,
          goalsAgainst: 27,
          goalDifference: 0,
        },
        {
          position: 11,
          team: {
            id: 95,
            name: "Valencia CF",
            crestUrl: "https://crests.football-data.org/95.svg",
          },
          playedGames: 17,
          form: "",
          won: 6,
          draw: 7,
          lost: 4,
          points: 25,
          goalsFor: 27,
          goalsAgainst: 22,
          goalDifference: 5,
        },
        {
          position: 12,
          team: {
            id: 79,
            name: "CA Osasuna",
            crestUrl: "https://crests.football-data.org/79.svg",
          },
          playedGames: 17,
          form: "",
          won: 6,
          draw: 5,
          lost: 6,
          points: 23,
          goalsFor: 18,
          goalsAgainst: 20,
          goalDifference: -2,
        },
        {
          position: 13,
          team: {
            id: 88,
            name: "Levante UD",
            crestUrl: "https://crests.football-data.org/88.svg",
          },
          playedGames: 17,
          form: "",
          won: 5,
          draw: 7,
          lost: 5,
          points: 22,
          goalsFor: 22,
          goalsAgainst: 25,
          goalDifference: -3,
        },
        {
          position: 14,
          team: {
            id: 82,
            name: "Getafe CF",
            crestUrl: "https://crests.football-data.org/82.svg",
          },
          playedGames: 17,
          form: "",
          won: 5,
          draw: 6,
          lost: 6,
          points: 21,
          goalsFor: 13,
          goalsAgainst: 11,
          goalDifference: 2,
        },
        {
          position: 15,
          team: {
            id: 285,
            name: "Elche CF",
            crestUrl: "https://crests.football-data.org/285.svg",
          },
          playedGames: 17,
          form: "",
          won: 4,
          draw: 8,
          lost: 5,
          points: 20,
          goalsFor: 16,
          goalsAgainst: 21,
          goalDifference: -5,
        },
        {
          position: 16,
          team: {
            id: 263,
            name: "Deportivo Alavés",
            crestUrl: "https://crests.football-data.org/263.svg",
          },
          playedGames: 17,
          form: "",
          won: 5,
          draw: 5,
          lost: 7,
          points: 20,
          goalsFor: 15,
          goalsAgainst: 21,
          goalDifference: -6,
        },
        {
          position: 17,
          team: {
            id: 299,
            name: "SD Huesca",
            crestUrl: "https://crests.football-data.org/299.svg",
          },
          playedGames: 17,
          form: "",
          won: 4,
          draw: 6,
          lost: 7,
          points: 18,
          goalsFor: 16,
          goalsAgainst: 21,
          goalDifference: -5,
        },
        {
          position: 18,
          team: {
            id: 264,
            name: "Cádiz CF",
            crestUrl: "https://crests.football-data.org/264.svg",
          },
          playedGames: 17,
          form: "",
          won: 4,
          draw: 5,
          lost: 8,
          points: 17,
          goalsFor: 14,
          goalsAgainst: 26,
          goalDifference: -12,
        },
        {
          position: 19,
          team: {
            id: 250,
            name: "Real Valladolid CF",
            crestUrl: "https://crests.football-data.org/250.svg",
          },
          playedGames: 17,
          form: "",
          won: 3,
          draw: 7,
          lost: 7,
          points: 16,
          goalsFor: 18,
          goalsAgainst: 26,
          goalDifference: -8,
        },
        {
          position: 20,
          team: {
            id: 278,
            name: "SD Eibar",
            crestUrl: "https://crests.football-data.org/278.svg",
          },
          playedGames: 17,
          form: "",
          won: 2,
          draw: 6,
          lost: 9,
          points: 12,
          goalsFor: 11,
          goalsAgainst: 19,
          goalDifference: -8,
        },
      ],
    },
    {
      stage: "REGULAR_SEASON",
      type: "AWAY",
      group: null,
      table: [
        {
          position: 1,
          team: {
            id: 81,
            name: "FC Barcelona",
            crestUrl: "https://crests.football-data.org/81.svg",
          },
          playedGames: 17,
          form: "",
          won: 12,
          draw: 1,
          lost: 4,
          points: 37,
          goalsFor: 37,
          goalsAgainst: 15,
          goalDifference: 22,
        },
        {
          position: 2,
          team: {
            id: 86,
            name: "Real Madrid CF",
            crestUrl: "https://crests.football-data.org/86.svg",
          },
          playedGames: 17,
          form: "",
          won: 10,
          draw: 6,
          lost: 1,
          points: 36,
          goalsFor: 29,
          goalsAgainst: 14,
          goalDifference: 15,
        },
        {
          position: 3,
          team: {
            id: 78,
            name: "Club Atlético de Madrid",
            crestUrl: "https://crests.football-data.org/78.svg",
          },
          playedGames: 17,
          form: "",
          won: 10,
          draw: 4,
          lost: 3,
          points: 34,
          goalsFor: 24,
          goalsAgainst: 13,
          goalDifference: 11,
        },
        {
          position: 4,
          team: {
            id: 559,
            name: "Sevilla FC",
            crestUrl: "https://crests.football-data.org/559.svg",
          },
          playedGames: 17,
          form: "",
          won: 10,
          draw: 3,
          lost: 4,
          points: 33,
          goalsFor: 24,
          goalsAgainst: 16,
          goalDifference: 8,
        },
        {
          position: 5,
          team: {
            id: 92,
            name: "Real Sociedad de Fútbol",
            crestUrl: "https://crests.football-data.org/92.svg",
          },
          playedGames: 17,
          form: "",
          won: 7,
          draw: 5,
          lost: 5,
          points: 26,
          goalsFor: 23,
          goalsAgainst: 15,
          goalDifference: 8,
        },
        {
          position: 6,
          team: {
            id: 94,
            name: "Villarreal CF",
            crestUrl: "https://crests.football-data.org/94.svg",
          },
          playedGames: 17,
          form: "",
          won: 6,
          draw: 7,
          lost: 4,
          points: 25,
          goalsFor: 28,
          goalsAgainst: 19,
          goalDifference: 9,
        },
        {
          position: 7,
          team: {
            id: 264,
            name: "Cádiz CF",
            crestUrl: "https://crests.football-data.org/264.svg",
          },
          playedGames: 17,
          form: "",
          won: 6,
          draw: 5,
          lost: 6,
          points: 23,
          goalsFor: 15,
          goalsAgainst: 23,
          goalDifference: -8,
        },
        {
          position: 8,
          team: {
            id: 90,
            name: "Real Betis Balompié",
            crestUrl: "https://crests.football-data.org/90.svg",
          },
          playedGames: 17,
          form: "",
          won: 6,
          draw: 4,
          lost: 7,
          points: 22,
          goalsFor: 19,
          goalsAgainst: 26,
          goalDifference: -7,
        },
        {
          position: 9,
          team: {
            id: 558,
            name: "RC Celta de Vigo",
            crestUrl: "https://crests.football-data.org/558.svg",
          },
          playedGames: 17,
          form: "",
          won: 3,
          draw: 8,
          lost: 6,
          points: 17,
          goalsFor: 19,
          goalsAgainst: 24,
          goalDifference: -5,
        },
        {
          position: 10,
          team: {
            id: 79,
            name: "CA Osasuna",
            crestUrl: "https://crests.football-data.org/79.svg",
          },
          playedGames: 17,
          form: "",
          won: 4,
          draw: 5,
          lost: 8,
          points: 17,
          goalsFor: 13,
          goalsAgainst: 21,
          goalDifference: -8,
        },
        {
          position: 11,
          team: {
            id: 88,
            name: "Levante UD",
            crestUrl: "https://crests.football-data.org/88.svg",
          },
          playedGames: 17,
          form: "",
          won: 4,
          draw: 4,
          lost: 9,
          points: 16,
          goalsFor: 16,
          goalsAgainst: 23,
          goalDifference: -7,
        },
        {
          position: 12,
          team: {
            id: 250,
            name: "Real Valladolid CF",
            crestUrl: "https://crests.football-data.org/250.svg",
          },
          playedGames: 17,
          form: "",
          won: 2,
          draw: 9,
          lost: 6,
          points: 15,
          goalsFor: 14,
          goalsAgainst: 20,
          goalDifference: -6,
        },
        {
          position: 13,
          team: {
            id: 83,
            name: "Granada CF",
            crestUrl: "https://crests.football-data.org/83.svg",
          },
          playedGames: 17,
          form: "",
          won: 4,
          draw: 3,
          lost: 10,
          points: 15,
          goalsFor: 19,
          goalsAgainst: 34,
          goalDifference: -15,
        },
        {
          position: 14,
          team: {
            id: 278,
            name: "SD Eibar",
            crestUrl: "https://crests.football-data.org/278.svg",
          },
          playedGames: 17,
          form: "",
          won: 3,
          draw: 5,
          lost: 9,
          points: 14,
          goalsFor: 15,
          goalsAgainst: 27,
          goalDifference: -12,
        },
        {
          position: 15,
          team: {
            id: 77,
            name: "Athletic Club",
            crestUrl: "https://crests.football-data.org/77.svg",
          },
          playedGames: 16,
          form: "",
          won: 2,
          draw: 7,
          lost: 7,
          points: 13,
          goalsFor: 16,
          goalsAgainst: 20,
          goalDifference: -4,
        },
        {
          position: 16,
          team: {
            id: 82,
            name: "Getafe CF",
            crestUrl: "https://crests.football-data.org/82.svg",
          },
          playedGames: 17,
          form: "",
          won: 3,
          draw: 4,
          lost: 10,
          points: 13,
          goalsFor: 13,
          goalsAgainst: 29,
          goalDifference: -16,
        },
        {
          position: 17,
          team: {
            id: 299,
            name: "SD Huesca",
            crestUrl: "https://crests.football-data.org/299.svg",
          },
          playedGames: 17,
          form: "",
          won: 2,
          draw: 6,
          lost: 9,
          points: 12,
          goalsFor: 16,
          goalsAgainst: 29,
          goalDifference: -13,
        },
        {
          position: 18,
          team: {
            id: 95,
            name: "Valencia CF",
            crestUrl: "https://crests.football-data.org/95.svg",
          },
          playedGames: 17,
          form: "",
          won: 2,
          draw: 5,
          lost: 10,
          points: 11,
          goalsFor: 16,
          goalsAgainst: 29,
          goalDifference: -13,
        },
        {
          position: 19,
          team: {
            id: 263,
            name: "Deportivo Alavés",
            crestUrl: "https://crests.football-data.org/263.svg",
          },
          playedGames: 17,
          form: "",
          won: 2,
          draw: 5,
          lost: 10,
          points: 11,
          goalsFor: 13,
          goalsAgainst: 31,
          goalDifference: -18,
        },
        {
          position: 20,
          team: {
            id: 285,
            name: "Elche CF",
            crestUrl: "https://crests.football-data.org/285.svg",
          },
          playedGames: 17,
          form: "",
          won: 2,
          draw: 4,
          lost: 11,
          points: 10,
          goalsFor: 13,
          goalsAgainst: 29,
          goalDifference: -16,
        },
      ],
    },
  ],
};
